--- # Component class tag names
  fileInput: "plenix.util.io.FileInputStreamSource"
  fileOutput: "plenix.util.io.FileOutputStreamSource"

  field: "plenix.record.util.FieldSpec"
  fixedField: "plenix.record.util.FixedFieldSpec"

  csvProducer: "plenix.record.csv.CSVRecordSource"
  csvConsumer: "plenix.record.csv.CSVRecordDestination"

  fixedLengthProducer: "plenix.record.fixed.FixedLengthRecordSource"
  fixedLengthConsumer: "plenix.record.fixed.FixedLengthRecordDestination"

  jdbcProducer: "plenix.record.jdbc.JDBCRecordSource"
  jdbcConsumer: "plenix.record.jdbc.JDBCRecordDestination"

  xbaseProducer: "plenix.record.xbase.XBaseRecordSource"
  xbaseConsumer: "plenix.record.xbase.XBaseRecordDestination"

  saxConsumer: "plenix.record.xml.sax.SAXRecordDestination"
  
--- # Property element names
  plenix.record.util.FieldSpecHolder:
    fields: "plenix.record.util.FieldSpec"
  plenix.record.fixed.FixedLengthCopierComponent: # Report bug -> property names seem to be global across target classes
    fixedFields: "plenix.record.util.FixedFieldSpec"
    